name: '420'
favicon: null
layout_spectrum: 0.18974392511881888
typography_spectrum: 0.18052235152572393
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.6740971335675567
  lightness: 0.8477243480738252
  saturation: 0.52809745259583
  rhythmicContrast: 0.7217132523655891
purpose: []
